Relationships = {
    [`Bobcat`] = "COUGAR",
    [`BrnBear`] = "COUGAR",
    [`Crocodile`] = "COUGAR",
    [`Donkey`] = "DOMESTIC_ANIMAL",
    [`Eagle`] = "HEN",
    [`Elephant`] = "DOMESTIC_ANIMAL",
    [`Falcon`] = "DOMESTIC_ANIMAL",
    [`Fullhorse`] = "DOMESTIC_ANIMAL",
    [`Greatwhite`] = "SHARK",
    [`Lepoard`] = "COUGAR",
    [`Macaw`] = "DOMESTIC_ANIMAL",
    [`Malelion`] = "COUGAR",
    [`Owl`] = "HEN",
    [`Parrot`] = "DOMESTIC_ANIMAL",
    [`Rangehorse`] = "WILD_ANIMAL",
    [`RedPanda`] = "WILD_ANIMAL",
    [`Skunk`] = "WILD_ANIMAL",
    [`Sparrow`] = "WILD_ANIMAL",
    [`Tigershark`] = "SHARK",
    [`Vulture`] = "WILD_ANIMAL",
    [`Warbler`] = "WILD_ANIMAL",
    [`wolf`] = "COUGAR",
    [`Younghorse`] = "DOMESTIC_ANIMAL",
    [`A_C_HumpBack`] = "WILD_ANIMAL",
    [`A_C_Seagull`] = "DOMESTIC_ANIMAL",
    [`A_C_Fish`] = "WILD_ANIMAL",
    [`A_C_Pigeon`] = "WILD_ANIMAL",
    [`A_C_Chop_02`] = "WILD_ANIMAL",
    [`A_C_Cat_01`] = "WILD_ANIMAL",
    [`A_C_Hen`] = "HEN",
    [`A_C_Rat`] = "WILD_ANIMAL",
    [`A_C_Stingray`] = "WILD_ANIMAL",
    [`A_C_Rottweiler`] = "DOMESTIC_ANIMAL",
    [`A_C_Retriever`] = "DOMESTIC_ANIMAL",
    [`A_C_Poodle`] = "DOMESTIC_ANIMAL",
    [`A_C_Rhesus`] = "WILD_ANIMAL",
    [`A_C_Cow`] = "DOMESTIC_ANIMAL",
    [`A_C_Chimp`] = "WILD_ANIMAL",
    [`A_C_Pig`] = "DOMESTIC_ANIMAL",
    [`A_C_Cormorant`] = "DOMESTIC_ANIMAL",
    [`A_C_MtLion`] = "COUGAR",
    [`A_C_Chop`] = "WILD_ANIMAL",
    [`A_C_Coyote`] = "COUGAR",
    [`A_C_Pug`] = "DOMESTIC_ANIMAL",
    [`A_C_Boar`] = "WILD_ANIMAL",
    [`A_C_SharkHammer`] = "SHARK",
    [`A_C_SharkTiger`] = "SHARK",
    [`A_C_Deer`] = "WILD_ANIMAL",
    [`A_C_Dolphin`] = "DOMESTIC_ANIMAL",
    [`A_C_shepherd`] = "DOMESTIC_ANIMAL",
    [`A_C_Husky`] = "DOMESTIC_ANIMAL",
    [`A_C_Crow`] = "WILD_ANIMAL",
    [`A_C_Rabbit_01`] = "DOMESTIC_ANIMAL",
    [`A_C_KillerWhale`] = "SHARK",
    [`A_C_Westy`] = "DOMESTIC_ANIMAL",
    [`A_C_Chickenhawk`] = "DOMESTIC_ANIMAL",
    [`A_C_Panther`] = "COUGAR",
}

--[[ RELATIONSHIPS
    HEN
    WILD_ANIMAL
    SHARK
    COUGAR
    GUARD_DOG
    DOMESTIC_ANIMAL
    DEER
]]